server:
  -port: 8080
  -servlet:
    -context-path: /myboot
spring:
  -datasource:
    -url: jdbc:mysql://localhost:3306/his?useSSL=true&serverTimezone=UTC&characterEncoding=utf-8
    -username: root
    -password: root
    -driver-class-name: com.mysql.jdbc.Driver
  -mvc:
    -view:
      -suffix: .jsp
      -prefix: /WEB-INF/view/
    -static-path-pattern: /**
  -resources:
       -static-locations: ["classpath:/META-INF/resources/","classpath:/resources/",
        "classpath:/static/","classpath:/public/","file:D:/appach/"]
  -jpa:
      -database: mysql
  -http:
      -encoding:
        -charset: utf-8
#devtools:
#  restart:
#    enabled: true #热部署生效
#    #设置重启的目录
#    additional-paths: src/main/java
#    exclude: WEB-INF/** #classpath目录下的WEB-INF文件夹内容修改不重启
mybatis:
  -mapper-locations: classpath*:mapper/*.xml
  -type-aliases-package: com.youma.vo
logging:
  -level:
    -com.youma.dao: debug


